refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S):<20} {M:>20.30}:{L:>3} {h({l})}    {m}\n"
  logstash:
    kind: logstash
    hostname: 127.0.0.1
    port: 50000
    buffer_size: 100
    log_queue_len: 1000
    buffer_lifetime: 1s
root:
  level: debug
  appenders:
    - stdout
    - logstash
