management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: app-meta-service
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
  level:
    com.goracz.metaservice: DEBUG
