name: CI / Control Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'control-service/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'control-service/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Build Control Service
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        build-root-directory: control-service
      env:
        KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        SENTRY_TRACES_SAMPLE_RATE: ${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        INTERFACE_URI: ${{ secrets.INTERFACE_URI }}
        META_SERVICE_URI: ${{ secrets.META_SERVICE_URI }}
